language: objective-c
osx_image: xcode11.4

before_install:
  # Fix Travis  xcodebuild exited with 65 https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone 8 (11" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

install:
  - cd Tests
  - bundle install
  - bundle exec pod install

script:
  - set -o pipefail
  - xcodebuild -workspace libidn.xcworkspace -scheme "libidn (iOS)" -destination "'platform=iOS Simulator,name=iPhone 11,OS=13.4'" -sdk iphonesimulator build | xcpretty -c
  - xcodebuild -workspace libidn.xcworkspace -scheme libidnTests -destination "'platform=macOS,arch=x86_64'" -sdk macosx -arch x86_64 test | xcpretty -c
  - xcodebuild -workspace libidn.xcworkspace -scheme libidnTestsPods -destination "'platform=macOS,arch=x86_64'" -sdk macosx -arch x86_64 test | xcpretty -c
  - xcodebuild -workspace libidn.xcworkspace -scheme "libidn (tvOS)" -destination "'platform=tvOS Simulator,name=Apple TV,OS=13.4'" -sdk appletvsimulator -arch x86_64 build | xcpretty -c
  - xcodebuild -workspace libidn.xcworkspace -scheme "libidn (watchOS)" -destination "platform=watchos Simulator,name=Apple Watch Series 4 - 44mm,OS=6.2," -sdk watchos build | xcpretty -c
  - swift build -c release
  - swift test -c release
